version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/front/
hooks:
  AfterInstall:
    - location: /afterInstall.sh
      timeout: 200
      runas: ec2-user
      #    - location: scripts/generate_config.sh
      #      timeout: 150
      #      runas: ec2-user

  ApplicationStart:
    - location: /applicationRun.sh
      timeout: 300
      runas: ec2-user
      
permissions:
    - object: /
      pattern: "**"
      owner: ec2-user
      group: ec2-user
